measurement:
  noise: 
    name: gaussian
    sigma: 0.03
  operator:
    name: gaussian_blur
    kernel_size: 61
    intensity: 3.0
  kernel_opt:
    kernel: gaussian
    kernel_size: 61
    intensity: 3.0

fmplug:
  data_folder: "/scratch.global/wan01530/FMPlug/dataset_deg_1024/"
  save_folder: "/scratch.global/wan01530/FMPlug/experiment-DGP-Full"
  img_size: 512

  method: "heun2"
  alpha: 0.8
  t_end: 0.00
  NFE: 3
  batch_size: 1
  guidance_scale: 0.0
  lr: [0.02, 0.01, 0.005, 0.002]
  # lr: [0.2, 0.1, 0.05, 0.02]
  # lr_dec: [0.0001, 0.00005, 0.00002]
  lr_dec: [0.001, 0.0005, 0.0002]
  lr_t_ada: 0.1
  decay_factor: 0.98
  epochs: 2000
  loss_multiplier: 1.0
  vae_weight: 0.0
  lpips_weight: 0.0
  TV_reg_weight: 0.0
  loss_fn: "l1"
  data_type: torch.bfloat16
  optimizer_select: "adam"
  
  es_window_size: 50
  es_patience: 25
  es_min_epochs: 200
  es_delta: 0.00001

  finetune_decoder_interval: 100