noise:
  name: "gaussian"
  sigma: 0.05

fmplug:
  data_folder: "/scratch.global/wan01530/FMPlug/dataset_deg"
  task: "super_resolution"
  img_size: 512
  scale_factor: 4

  alpha: 0.2
  t_end: 0.00
  NFE: 3
  batch_size: 1
  guidance_scale: 1.0
  lr: 0.1
  lr_t_ada: 2.0
  epochs: 5000
  loss_multiplier: 1.0
  lpips_weight: 1.0
  TV_reg_weight: 0.00001
  loss_fn: "l1"
  data_type: torch.float32
  prompt: "a high quality photo of animal, bush, close-up, fox, grass, green, greenery, hide, panda, red, red panda, stare"


