config:
  image_size: 512
  scale_factor: 4
  num_inference_steps: 3
  batch_size: 1
  guidance_scale: 2.0
  lr: 1.0
  epochs: 25
  loss_multiplier: 100.0
  loss_fn: "mse"
  max_iter: 20
  timesteps_type: "linear"
  t_start: 999.0
  t_end: 0.05
  prompt: "a high quality photo of animal, bush, close-up, fox, grass, green, greenery, hide, panda, red, red panda, stare"