fmplug:
  NFE: 3
  TV_reg_weight: 0.0
  alpha: 0.5
  batch_size: 1
  data_type: torch.float32
  decay_factor: 0.98
  epochs: 1000
  es_delta: 1.0e-09
  es_min_epochs: 20
  es_patience: 50
  es_window_size: 50
  finetune_decoder_blocks_interval: 100
  guidance_scale: 0.0
  img_size: 512
  is_calibrate: True
  is_gauss_reg: True
  loss_fn: mse
  loss_multiplier: 1000.0
  lpips_weight: 0.0
  lr_alpha_ada: 0.05
  lr_dec: []
  lr_prior_weight: 0.1
  lr_z:
  - 0.1
  method: heun2
  optimizer_select: adam
  save_folder: /scratch.global/wan01530/FMPlug/experiment-FMPlug-OT-W-R-MRI
  t_end: 0.0
  vae_weight: 0.0
measurement:
  operator:
    name: MRI
    scale_factor: 1
