measurement:
  noise: 
    name: gaussian
    sigma: 0.03
  operator:
    name: inpainting
  mask_opt:
    mask_type: random
    mask_prob_range: [0.7, 0.7]  # for random
    image_size: 1024

fmplug:
  data_folder: "/scratch.global/wan01530/FMPlug/dataset_deg/"
  save_folder: "/scratch.global/wan01530/FMPlug/experiment-ES100"
  img_size: 1024
  scale_factor: 4

  method: "heun2"
  alpha: 0.2
  t_end: 0.05
  NFE: 1
  batch_size: 1
  guidance_scale: 1.0
  lr: 0.002
  lr_t_ada: 0.05
  decay_factor: 0.98
  epochs: 1000
  loss_multiplier: 1.0
  vae_weight: 0.0
  lpips_weight: 0.0
  TV_reg_weight: 0.0
  loss_fn: "l1"
  data_type: torch.bfloat16
  optimizer_select: "adam"
  
  es_window_size: 100
  es_patience: 25
  es_min_epochs: 1000
  es_delta: 0.000001