measurement:
  noise: 
    name: gaussian
    sigma: 0.03
  operator:
    name: super_resolution
    in_shape: [1, 3, 512, 512]
    scale_factor: 4

fmplug:
  data_folder: "/scratch.global/wan01530/FMPlug/dataset_deg/"
  save_folder: "/scratch.global/wan01530/FMPlug/experiment-ES100"
  img_size: 512
  scale_factor: 4

  method: "heun2"
  alpha: 0.2
  t_end: 0.05
  NFE: 3
  batch_size: 1
  guidance_scale: 2.0
  lr: 0.1
  lr_t_ada: 0.05
  decay_factor: 0.98
  epochs: 1000
  loss_multiplier: 1.0
  vae_weight: 0.0
  lpips_weight: 0.0
  TV_reg_weight: 0.0
  loss_fn: "l1"
  data_type: torch.bfloat16
  optimizer_select: "adam"

  es_window_size: 100
  es_patience: 25
  es_min_epochs: 100
  es_delta: 0.000001
