measurement:
  noise: 
    name: gaussian
    sigma: 0.03
  operator:
    name: gaussian_blur
    kernel_size: 61
    intensity: 3.0
  kernel_opt:
    kernel: gaussian
    kernel_size: 61
    intensity: 3.0

fmplug:
  data_folder: "/scratch.global/wan01530/FMPlug/dataset_deg_1024"
  save_folder: "/scratch.global/wan01530/FMPlug/experiment-FMPlug-OT-W-Calibrated-Prompt"
  img_size: 512

  method: "heun2"
  alpha: 0.8
  t_end: 0.00
  NFE: 3
  batch_size: 1
  guidance_scale: 2.0
  lr_z: [0.5, 0.2]
  lr_dec: []
  lr_t_ada: 0.01
  lr_alpha_ada: 0.005
  decay_factor: 0.95
  epochs: 1000
  loss_multiplier: 1.0
  vae_weight: 0.0
  lpips_weight: 0.0
  TV_reg_weight: 0.0
  is_gauss_reg: False
  is_calibrate: True
  loss_fn: "mse"
  data_type: torch.bfloat16
  optimizer_select: "adam"
  
  es_window_size: 50
  es_patience: 50
  es_min_epochs: 100
  es_delta: 0.000000001

  finetune_decoder_blocks_interval: 100